Issue noisediode deactivation to happen now
ska-sa/astrokat pull request #118
Opened 2023-08-23 12:57 UTC by bngcebetsha

As reported in [OPS-2080](https://skaafrica.atlassian.net/browse/OPS-2080), the observation script switches the noisediodes off at the end of observations. There have been issues on site where lost connection to a receptor results in failure to switch the noisediodes off on all other antennas on the array, which reports a failure. Here we attempt to mitigate that by using the current time as the time to reset the noisediode.

## PLEASE NOTE
We still need to test this, so please take this as a draft PR.

JIRA: [MT-3844](https://skaafrica.atlassian.net/browse/MT-3844)

[OPS-2080]: https://skaafrica.atlassian.net/browse/OPS-2080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MT-3844]: https://skaafrica.atlassian.net/browse/MT-3844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-08-30 16:25 UTC, ludwigschwardt requested changes
I'm still going through this but I suspect there is a much simpler way to do this... See e.g. https://skaafrica.atlassian.net/browse/OPS-2790?focusedCommentId=164604

2023-08-30 16:25 UTC, ludwigschwardt commented on astrokat/observe_main.py
> +        noisediode.nd_reset(self.array, time.time())
There is a special timestamp called `"now"` that simplifies this a lot...

2023-08-30 16:25 UTC, ludwigschwardt commented on astrokat/noisediode.py
> +    for ant in antennas:
There is no need to loop over antennas... Use the `kat.ants` group instead. I.e. `kat.ants.req.dig_noise_source(timestamp, switch)`.

2023-11-01 11:23 UTC, lanceWilliams commented
@ludwigschwardt just following up on this: so would you be ok if we removed the noise diode off command in https://github.com/ska-sa/astrokat/blob/f7e29ce091100a6041c61a8f3974f7b6a2611adf/astrokat/observe_main.py#L301  (and rely on session to do it) and then retain the function Buntu has created to turn noisediodes off with the 'now' timestamp on the way out of the schedule block in the __exit__  function ?

2023-11-01 11:43 UTC, ludwigschwardt requested changes

2023-11-01 11:43 UTC, ludwigschwardt commented on astrokat/noisediode.py
> +             timestamp,
You say in the docstring that this is optional but there is no default value... I would just make the default value "now".

2023-11-01 11:43 UTC, ludwigschwardt commented on astrokat/noisediode.py
> +    user_logger.info('Resetting all noise diodes')
I would probably report whether you are switching it on or off.

2023-11-01 11:43 UTC, ludwigschwardt commented on astrokat/noisediode.py
> +    timestamp : float
I don't think it returns anything.

2023-11-01 11:47 UTC, ludwigschwardt commented
Lance, your suggestion makes sense. I don't switch them off on the way out, just on the way in.

2023-11-06 09:08 UTC, ludwigschwardt approved these changes

2023-11-07 13:47 UTC, merged